from app.models import db, Post, environment, SCHEMA

def seed_posts():
    post1 = Post(user_id="1", body="This is my first post on here. Looking forward to meeting everyone.")
    post2 = Post(user_id="3", body="An office is not for dying. An office is a place for living life to the fullest, to the max, to… an office is a place where dreams come true.")
    post3 = Post(user_id="1", body="I'm bored. Someone hire me.")
    post4 = Post(user_id="2", body="Let's be nice to one another")
    post5 = Post(user_id="3", body='Sometimes I"ll start a sentence, and I don"t even know where it"s going. I just hope I find it along the way.')
    post6 = Post(user_id="2", body="How to use LinkedUp? Connect with everyone!")
    post7 = Post(user_id="3", body="I love Linkedup more than LinkedIn.")
    post8 = Post(user_id="2", body='You guys I"m, like, really smart now. You don"t even know. You could ask me, "Kelly what"s the biggest company in the world?" And I"d be like, "Blah blah blah, blah blah blah, blah blah blah." Giving you the exact right answer.')
    post9 = Post(user_id="4", body='I may not have done so hot on my customer reviews this year.')
    post10 = Post(user_id="2", body='My resolution was to get more attention.')
    post11 = Post(user_id="2", body='My Sometimes I get so bored I just want to scream, and then sometimes I actually do scream. I just sort of feel out what the situation calls for.')
    post12 = Post(user_id="3", body='Wikipedia is the best thing ever. Anyone in the world can write anything they want about any subject. So you know you are getting the best possible information.')
    post13 = Post(user_id="2", body='This day is bananas, B-A-N-A-N-A-S. 🍌')
    post14 = Post(user_id="3", body='Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me.')
    post15 = Post(user_id="3", body='Guess what, I have flaws. What are they? Oh, I don"t know. I sing in the shower. Sometimes I spend too much time volunteering. Occasionally I"ll hit somebody with my car. So sue me.')
    post16 = Post(user_id="4", body='I am about to do something very bold in this job that I"ve never done before: try.')
    post17 = Post(user_id="3", body='Do I have a special someone? Well, yeah, of course. A bunch of "em. My employees.')
    post18 = Post(user_id="3", body='The most sacred thing I do is care and provide for my workers, my family. I give them money. I give them food. Not directly, but through the money.')
    post19 = Post(user_id="3", body='Now, you may look around and see two groups here. White-collar, blue-collar. But I don"t see it that way. And you know why not? Because I am collar-blind.')

    db.session.add(post1)
    db.session.add(post2)
    db.session.add(post3)
    db.session.add(post4)
    db.session.add(post5)
    db.session.add(post6)
    db.session.add(post7)
    db.session.add(post8)
    db.session.add(post9)
    db.session.add(post10)
    db.session.add(post11)
    db.session.add(post12)
    db.session.add(post13)
    db.session.add(post14)
    db.session.add(post15)
    db.session.add(post16)
    db.session.add(post17)
    db.session.add(post18)
    db.session.add(post19)
    db.session.commit()

def undo_posts():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.posts RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM posts")

    db.session.commit()
